### ISSUE TITLE
Changing parts list

### ISSUE THREAD

**Issue by PLSKevin** [team4eng/Civil_3D#13]
might have some useful info here https://forums.autodesk.com/t5/civil-3d-forum/editing-parts-list/td-p/9004042

But this (see link below) we need to fully understand and have a means of deploying, do we use a server location or a local. I recommend local, but the auto-update start c3d script you have should update the local folder when launching c3d,

https://knowledge.autodesk.com/support/civil-3d/learn-explore/caas/CloudHelp/cloudhelp/2020/ENU/Civil3D-BestPractices/files/GUID-3414A18B-BF83-4233-B9D4-2CCA47707D53-htm.html

**Comment by pkohut** [comment]
This issue can be closed if you think it has been adequately addressed.
