### ISSUE TITLE
Engineers Stamp

### ISSUE THREAD

**Issue by PLSKevin** [team4eng/Civil_3D#20]
The x-PROJ-G-TITL needs to have Mark's stamp, but I don't think I want the stamp resident in the drawing. I THINK I want it as a xref in the TITL drawing. I think I want it xrefed in a specific path, not relative, then, if another licensed individual wanted to put their stamp in, then they just update the xref to the location of their stamp.

**Comment by pkohut** [comment]
These should be moved to the R drive

**Comment by pkohut** [comment]
Should we add a subdirectory in to R:\Xrefs to hold stamps???
```
R:\Xrefs
```

**Comment by pkohut** [comment]
I've taken the stamps for Mike, Mark, Jeff, Kyle, Kevin, and cleaned up the blocks and placed into the
R:\Xrefs\Stamps
directory.

These stamps have all elements on layer 0 and color by layer, no signatures, or sealed date field.
