### ISSUE TITLE
New Line layers for DWS

### ISSUE THREAD

**Issue by PLSKevin** [team4eng/Civil_3D#23]
Copy of V-TOPO-BRKL change the following, Name: V-TOPO-TOP Description: Survey: Topography TOP
Copy of V-TOPO-BRKL change the following, Name: V-TOPO-TOE Description: Survey: Topography TOE

How can we modify layer states to not show these layers?

**Comment by pkohut** [comment]
I've add to v-topo-top and v-topo-toe layers with attributes for topo-brkl.

Will create a new issue to address modify of layer states.

**Comment by PLSKevin** [comment]
ADD layers V-NODE-STAK and V-NODE-CALC

**Comment by PLSKevin** [comment]
Also add V-STAK-SYMB

**Comment by pkohut** [comment]
Added to the standards file these new layers with color 255
```
V-NODE-STAK   --- Survey: Staked Construction Points
V-NODE-CALC   --- Survey: Calculated Points
V-STAK-SYMB    --- Survey: Staked Construction Point Symbols
```
